# Generated by Django 4.2.4 on 2023-08-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_audio_demo_original_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('new', 'New'), ('deals', 'Deals'), ('free', 'Free')], default='new', max_length=10),
        ),
    ]
