# Generated by Django 4.2.4 on 2023-08-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='audio_file',
            field=models.FileField(default=None, upload_to='audio/products'),
        ),
    ]
