# Generated by Django 4.2.4 on 2023-08-18 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_audio_file_audio_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio_Demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255)),
                ('original_file', models.FileField(upload_to='audio/products/original')),
                ('processed_file', models.FileField(upload_to='audio/products/processed')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_demo', to='products.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Audio_Files',
        ),
    ]
