# Generated by Django 4.2.4 on 2023-08-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_audio_demo_delete_audio_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio_demo',
            name='original_file',
            field=models.FileField(blank=True, null=True, upload_to='audio/products/original'),
        ),
        migrations.AlterField(
            model_name='audio_demo',
            name='processed_file',
            field=models.FileField(blank=True, null=True, upload_to='audio/products/processed'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/products'),
        ),
    ]
